package io.github.kamui2040.vectorint.receipt

internal enum class ReceiptVendorCategory {
    GROCERY,
    DRUGSTORE,
    FASHION,
    SHOES,
    ELECTRONICS,
    HOME_AND_FURNITURE,
    DIY_AND_GARDEN,
    SPORTS,
    BOOKS_AND_STATIONERY,
    TOYS,
    PET_SUPPLIES,
    BEAUTY,
    DEPARTMENT_STORE,
    VARIETY_DISCOUNT,
    AUTOMOTIVE,
    FUEL,
}

internal data class ReceiptVendor(
    val id: String,
    val displayName: String,
    val category: ReceiptVendorCategory,
    val receiptAliases: Set<String>,
)

/**
 * Curated seed data for common physical retail chains in Germany.
 *
 * Aliases are intentional brand and receipt-header variants. Ambiguous short names, addresses,
 * tax identifiers, and guesses based on OCR errors do not belong in this catalogue.
 */
internal object GermanReceiptVendorCatalogue {
    val vendors: List<ReceiptVendor> =
        listOf(
            vendor("aldi-nord", "ALDI Nord", ReceiptVendorCategory.GROCERY, "ALDI NORD"),
            vendor("aldi-sued", "ALDI SÜD", ReceiptVendorCategory.GROCERY, "ALDI SUED"),
            vendor("edeka", "EDEKA", ReceiptVendorCategory.GROCERY),
            vendor("marktkauf", "Marktkauf", ReceiptVendorCategory.GROCERY),
            vendor(
                "netto-marken-discount",
                "Netto Marken-Discount",
                ReceiptVendorCategory.GROCERY,
                "NETTO MARKEN-DISCOUNT",
                "NETTO MARKENDISCOUNT",
            ),
            vendor(
                "netto-scottie",
                "Netto mit dem Scottie",
                ReceiptVendorCategory.GROCERY,
                "NETTO STAVENHAGEN",
                "NETTO APS & CO. KG",
            ),
            vendor("lidl", "Lidl", ReceiptVendorCategory.GROCERY),
            vendor("kaufland", "Kaufland", ReceiptVendorCategory.GROCERY),
            vendor("rewe", "REWE", ReceiptVendorCategory.GROCERY, "REWE MARKT", "REWE CENTER"),
            vendor("penny", "PENNY", ReceiptVendorCategory.GROCERY, "PENNY MARKT", "PENNY-MARKT"),
            vendor("nahkauf", "nahkauf", ReceiptVendorCategory.GROCERY),
            vendor("norma", "NORMA", ReceiptVendorCategory.GROCERY),
            vendor("globus", "GLOBUS", ReceiptVendorCategory.GROCERY, "GLOBUS MARKTHALLE"),
            vendor("hit", "HIT", ReceiptVendorCategory.GROCERY, "HIT MARKT"),
            vendor("famila", "famila", ReceiptVendorCategory.GROCERY),
            vendor("combi", "Combi", ReceiptVendorCategory.GROCERY, "COMBI VERBRAUCHERMARKT"),
            vendor("tegut", "tegut…", ReceiptVendorCategory.GROCERY, "TEGUT", "TEGUT..."),
            vendor("alnatura", "Alnatura", ReceiptVendorCategory.GROCERY, "ALNATURA SUPERNATUR MARKT"),
            vendor("denns-biomarkt", "denn's Biomarkt", ReceiptVendorCategory.GROCERY, "DENNS BIOMARKT"),
            vendor("bio-company", "BIO COMPANY", ReceiptVendorCategory.GROCERY),
            vendor("mix-markt", "Mix Markt", ReceiptVendorCategory.GROCERY, "MIX-MARKT"),
            vendor("v-markt", "V-Markt", ReceiptVendorCategory.GROCERY, "V MARKT"),
            vendor("diska", "diska", ReceiptVendorCategory.GROCERY),
            vendor("k-und-k", "K+K", ReceiptVendorCategory.GROCERY, "K+K KLAAS & KOCK"),
            vendor("wasgau", "WASGAU", ReceiptVendorCategory.GROCERY),
            vendor("cap-markt", "CAP Markt", ReceiptVendorCategory.GROCERY, "CAP-MARKT"),
            vendor("dm", "dm", ReceiptVendorCategory.DRUGSTORE, "DM-DROGERIE MARKT", "DM DROGERIE MARKT"),
            vendor("rossmann", "ROSSMANN", ReceiptVendorCategory.DRUGSTORE, "DIRK ROSSMANN"),
            vendor("mueller", "Müller", ReceiptVendorCategory.DRUGSTORE, "MUELLER"),
            vendor("budni", "BUDNI", ReceiptVendorCategory.DRUGSTORE, "BUDNIKOWSKY"),
            vendor("c-and-a", "C&A", ReceiptVendorCategory.FASHION, "C & A"),
            vendor("h-and-m", "H&M", ReceiptVendorCategory.FASHION, "H & M"),
            vendor("zara", "ZARA", ReceiptVendorCategory.FASHION),
            vendor("uniqlo", "UNIQLO", ReceiptVendorCategory.FASHION),
            vendor("primark", "Primark", ReceiptVendorCategory.FASHION),
            vendor("new-yorker", "New Yorker", ReceiptVendorCategory.FASHION, "NEWYORKER"),
            vendor("peek-und-cloppenburg", "Peek & Cloppenburg", ReceiptVendorCategory.FASHION, "P&C"),
            vendor("tk-maxx", "TK Maxx", ReceiptVendorCategory.FASHION, "TKMAXX"),
            vendor("kik", "KiK", ReceiptVendorCategory.FASHION, "KIK TEXTILIEN"),
            vendor("takko", "Takko Fashion", ReceiptVendorCategory.FASHION, "TAKKO"),
            vendor("ernstings-family", "Ernsting's family", ReceiptVendorCategory.FASHION, "ERNSTINGS FAMILY"),
            vendor("only", "ONLY", ReceiptVendorCategory.FASHION),
            vendor("vero-moda", "VERO MODA", ReceiptVendorCategory.FASHION),
            vendor("jack-and-jones", "JACK & JONES", ReceiptVendorCategory.FASHION, "JACK AND JONES"),
            vendor("s-oliver", "s.Oliver", ReceiptVendorCategory.FASHION, "S.OLIVER", "S OLIVER"),
            vendor("bonita", "BONITA", ReceiptVendorCategory.FASHION),
            vendor("mango", "MANGO", ReceiptVendorCategory.FASHION),
            vendor("reserved", "Reserved", ReceiptVendorCategory.FASHION),
            vendor("deichmann", "DEICHMANN", ReceiptVendorCategory.SHOES),
            vendor("snipes", "SNIPES", ReceiptVendorCategory.SHOES),
            vendor("foot-locker", "Foot Locker", ReceiptVendorCategory.SHOES, "FOOTLOCKER"),
            vendor("schuhcenter-siemes", "Schuhcenter Siemes", ReceiptVendorCategory.SHOES, "SCHUHCENTER"),
            vendor("tamaris", "Tamaris", ReceiptVendorCategory.SHOES),
            vendor("mediamarkt", "MediaMarkt", ReceiptVendorCategory.ELECTRONICS, "MEDIA MARKT"),
            vendor("saturn", "SATURN", ReceiptVendorCategory.ELECTRONICS),
            vendor("expert", "expert", ReceiptVendorCategory.ELECTRONICS),
            vendor("euronics", "EURONICS", ReceiptVendorCategory.ELECTRONICS),
            vendor("cyberport", "Cyberport", ReceiptVendorCategory.ELECTRONICS),
            vendor("ikea", "IKEA", ReceiptVendorCategory.HOME_AND_FURNITURE),
            vendor("jysk", "JYSK", ReceiptVendorCategory.HOME_AND_FURNITURE),
            vendor("xxxlutz", "XXXLutz", ReceiptVendorCategory.HOME_AND_FURNITURE, "XXXL LUTZ"),
            vendor("moemax", "mömax", ReceiptVendorCategory.HOME_AND_FURNITURE, "MOEMAX"),
            vendor("hoeffner", "Möbel Höffner", ReceiptVendorCategory.HOME_AND_FURNITURE, "HOEFFNER"),
            vendor("roller", "ROLLER", ReceiptVendorCategory.HOME_AND_FURNITURE),
            vendor("poco", "POCO", ReceiptVendorCategory.HOME_AND_FURNITURE, "POCO EINRICHTUNGSMARKT"),
            vendor("porta", "porta", ReceiptVendorCategory.HOME_AND_FURNITURE, "PORTA MOEBEL"),
            vendor("depot", "DEPOT", ReceiptVendorCategory.HOME_AND_FURNITURE),
            vendor("obi", "OBI", ReceiptVendorCategory.DIY_AND_GARDEN, "OBI MARKT"),
            vendor("bauhaus", "BAUHAUS", ReceiptVendorCategory.DIY_AND_GARDEN),
            vendor("hornbach", "HORNBACH", ReceiptVendorCategory.DIY_AND_GARDEN),
            vendor("toom", "toom Baumarkt", ReceiptVendorCategory.DIY_AND_GARDEN, "TOOM"),
            vendor("hagebaumarkt", "hagebaumarkt", ReceiptVendorCategory.DIY_AND_GARDEN, "HAGEBAU"),
            vendor("globus-baumarkt", "GLOBUS Baumarkt", ReceiptVendorCategory.DIY_AND_GARDEN),
            vendor("hellweg", "HELLWEG", ReceiptVendorCategory.DIY_AND_GARDEN),
            vendor("baywa", "BayWa Bau & Garten", ReceiptVendorCategory.DIY_AND_GARDEN, "BAYWA"),
            vendor("decathlon", "DECATHLON", ReceiptVendorCategory.SPORTS),
            vendor("intersport", "INTERSPORT", ReceiptVendorCategory.SPORTS),
            vendor("jd-sports", "JD Sports", ReceiptVendorCategory.SPORTS, "JD SPORTS FASHION"),
            vendor("sport-2000", "SPORT 2000", ReceiptVendorCategory.SPORTS),
            vendor("thalia", "Thalia", ReceiptVendorCategory.BOOKS_AND_STATIONERY),
            vendor("hugendubel", "Hugendubel", ReceiptVendorCategory.BOOKS_AND_STATIONERY),
            vendor("mcpaper", "McPaper", ReceiptVendorCategory.BOOKS_AND_STATIONERY, "MC PAPER"),
            vendor("idee", "idee. Creativmarkt", ReceiptVendorCategory.BOOKS_AND_STATIONERY, "IDEE CREATIVMARKT"),
            vendor("boesner", "boesner", ReceiptVendorCategory.BOOKS_AND_STATIONERY),
            vendor("smyths-toys", "Smyths Toys", ReceiptVendorCategory.TOYS, "SMYTHS"),
            vendor("rofu", "ROFU Kinderland", ReceiptVendorCategory.TOYS, "ROFU"),
            vendor("fressnapf", "Fressnapf", ReceiptVendorCategory.PET_SUPPLIES),
            vendor("futterhaus", "DAS FUTTERHAUS", ReceiptVendorCategory.PET_SUPPLIES, "FUTTERHAUS"),
            vendor("koelle-zoo", "Kölle Zoo", ReceiptVendorCategory.PET_SUPPLIES, "KOELLE ZOO"),
            vendor("douglas", "Douglas", ReceiptVendorCategory.BEAUTY, "PARFUEMERIE DOUGLAS"),
            vendor("sephora", "SEPHORA", ReceiptVendorCategory.BEAUTY),
            vendor("rituals", "Rituals", ReceiptVendorCategory.BEAUTY, "RITUALS COSMETICS"),
            vendor("galeria", "GALERIA", ReceiptVendorCategory.DEPARTMENT_STORE, "GALERIA KARSTADT KAUFHOF"),
            vendor("breuninger", "Breuninger", ReceiptVendorCategory.DEPARTMENT_STORE),
            vendor("action", "Action", ReceiptVendorCategory.VARIETY_DISCOUNT),
            vendor("tedi", "TEDi", ReceiptVendorCategory.VARIETY_DISCOUNT),
            vendor("woolworth", "Woolworth", ReceiptVendorCategory.VARIETY_DISCOUNT),
            vendor("euroshop", "EuroShop", ReceiptVendorCategory.VARIETY_DISCOUNT, "EURO SHOP"),
            vendor("maec-geiz", "Mäc-Geiz", ReceiptVendorCategory.VARIETY_DISCOUNT, "MAEC-GEIZ", "MAC-GEIZ"),
            vendor("sostrene-grene", "Søstrene Grene", ReceiptVendorCategory.VARIETY_DISCOUNT, "SOSTRENE GRENE"),
            vendor(
                "flying-tiger",
                "Flying Tiger Copenhagen",
                ReceiptVendorCategory.VARIETY_DISCOUNT,
                "FLYING TIGER",
            ),
            vendor("atu", "ATU", ReceiptVendorCategory.AUTOMOTIVE, "A.T.U", "AUTO-TEILE-UNGER"),
            vendor("pitstop", "pitstop", ReceiptVendorCategory.AUTOMOTIVE, "PIT STOP"),
            vendor("aral", "Aral", ReceiptVendorCategory.FUEL),
            vendor("shell", "Shell", ReceiptVendorCategory.FUEL),
            vendor("esso", "Esso", ReceiptVendorCategory.FUEL),
            vendor("totalenergies", "TotalEnergies", ReceiptVendorCategory.FUEL, "TOTAL ENERGIES"),
            vendor("jet", "JET", ReceiptVendorCategory.FUEL, "JET TANKSTELLE"),
            vendor("hem", "HEM", ReceiptVendorCategory.FUEL, "HEM TANKSTELLE"),
        )

    private fun vendor(
        id: String,
        displayName: String,
        category: ReceiptVendorCategory,
        vararg additionalAliases: String,
    ) = ReceiptVendor(
        id = id,
        displayName = displayName,
        category = category,
        receiptAliases = setOf(displayName, *additionalAliases),
    )
}
